### PR TITLE
feat: APIs to run application

### PR DESCRIPTION
**Pull request by s1n7ax**

### CODE REVIEW

**Comment by s1n7ax** [comment]
@atm1020 Hi, after multiple attmpts to fix tests, I decided to comment them out. For some reason they hang at following mock statement. Note sure why. May be you can check that since you have more experience in testing neovim stuff.

```
local vim = mock(vim, true)
```

**Comment by s1n7ax** [comment]
@atm1020 Sorry, It took way longer than it should. I will make sure future PRs are merge as soon as possible.

**Comment by atm1020** [comment]
@s1n7ax Hi, no problem! Im going to check the broken tests!

**Comment by atm1020** [comment]
@s1n7ax  Should I open an issue for this, or is it okay to just open a PR without a corresponding issue?

**Comment by s1n7ax** [comment]
@atm1020 A new issue and PR would be good

**Comment by atm1020** [comment]
@s1n7ax  I created a PR:  #140 with ticket: #139

**Pull request merged**
