### PR TITLE
update java-debug-adapter (Fix Error: link target com.microsoft.java.…

### PR DESCRIPTION
**Pull request by prastowoagungwidodo**
…debug.plugin-0.53.1.jar does not exist)

### CODE REVIEW

**Comment by s1n7ax** [comment]
@prastowoagungwidodo It does exist

https://open-vsx.org/extension/vscjava/vscode-java-debug/0.58.0

**Comment by domateus** [comment]
I have stumbled in this error today while installing nvim-java. Im still a beginner on how neovim and its configuration works. Is there a way for me to change locally this dependency version?

**Comment by w4ff3l** [comment]
> I have stumbled in this error today while installing nvim-java. Im still a beginner on how neovim and its configuration works. Is there a way for me to change locally this dependency version?

Yes, you can load a plugin from a directory. For example in lazy you can simply pass the path:
```lua
return {
    dir = '/path/to/your/plugin',
}
```
Or see the example in the [documentation](https://lazy.folke.io/spec/examples).

**Comment by s1n7ax** [comment]
java debug adapter comes from default mason registry. The shared libraries are hardcoded in the spec. When it's updated, it automatically breaks the older versions. Now, you can update the pinned version in the java config.
https://github.com/nvim-java/nvim-java?tab=readme-ov-file#wrench-configuration

**Pull request closed without merging**
